### ISSUE TITLE
Time, Severity, and Message should be merged after metadata in GoogleCloudLogger

### ISSUE THREAD

**Issue by StandardMikeBenza** [Nebo15/logger_json#111]
I recently debugged an issue where my log messages weren't showing up as expected.  I had introduced a log message that had `time` metadata (how long an operation took).  Since LoggerJSON.Formatters.GoogleCloudLogger [merges](https://github.com/Nebo15/logger_json/blob/987aabc835c6b37555aa62a6a76b6cac65ceed93/lib/logger_json/formatters/google_cloud_logger.ex#L48-L53) the metadata into the map of `time`, `severity`, and `message`, metadata `time` replaced the actual timestamp.  The same would happen for `severity` or `message`.

This should at a minimum be documented.  Ideally the `time`, `severity`, and `message` would be merged into the metadata.  A plus would be some way of warning that the original value had been overwritten and recording the original value.

**Comment by AndrewDryga** [comment]
Hello @StandardMikeBenza, this is the behaviour that is not specific to the package. Logger in the latest Elixir versions works on top of Erlang one and it supplies `time` as a metadata attribute to the formatted. Not sure if you can override it now or now, but closing since there is nothing we can do about it.
