### ISSUE TITLE
Logs show up as JSON and are not parsed by Stackdriver Logging

### ISSUE THREAD

**Issue by bjuretic** [Nebo15/logger_json#14]
Hi, I am using the latest code from `master` from K8S pod, with the following config:

```
config :logger_json, :backend,
       metadata: :all,
       formatter: LoggerJSON.Formatters.GoogleCloudLogger

config :logger,
       backends: [LoggerJSON],
       level: :info
```

The logs do show up in Stackdriver Logging, but they are not parsed, i.e. it doesn't know they are structured (JSON) and is treating them like plaintext. For example this is how it looks like visually:

```
2018-10-22 09:57:13.907 CEST
{"application":{"version":"0.5.17","name":"tzdata"},"log":"Tzdata has updated the release from 2018e to 2018f"}
```

Instead it should be parsed, and only show JSON once you click on it, AFAIK.

Is this because your JSON format is not as on https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry or something needs to be enabled/set somewhere to tell Stackdriver Logging to expect a structured log entry (so that it parses it)?

Thanks for the help!

**Comment by hoarf** [comment]
@bjuretic we are having the same issues, do you mind sharing if you managed to fix your problem and how?

**Comment by bjuretic** [comment]
@hoarf Sure. It is not an issue with this library, but that is how Stackdriver Loggins shows everything until you select which fields you want in the summary view. It is stupid, but that's how it works. Once you select the fields you want, it shows those fields + the JSON on the right.. so ti is a big mess, but that is the best it can be done, AFAIK.

**Comment by hoarf** [comment]
I am using google app engine with flexible environment. I think my issue is different than yours. My issue seems to be that the default logging agent is the one not parsing the payload as jsonPayload. Instead it yields a textPayload for the app stdout log.

**Comment by malcolmstill** [comment]
I think if you provide a `message` and `serviceContext` (see https://cloud.google.com/error-reporting/docs/formatting-error-messages) it will display only `message` when the log is collapsed which might be a easier to parse.

**Comment by AndrewDryga** [comment]
@malcolmstill the problem is that doc is only true when you use API to submit your logs. When they are collected as binaries by stackdriver agent or fluentd in GKE rules are different and there is a very limited number of things you can do.

See https://cloud.google.com/logging/docs/agent/configuration#special-fields.

**Comment by hawksight** [comment]
I've got an example that might be helpful here. We are also running on GKE and experienced the same issue as described here and in #13.

Here's an example log from one of our apps back in stackdriver.
![Screenshot 2019-11-27 at 16 11 11](https://user-images.githubusercontent.com/11051419/69741202-8aa00000-1132-11ea-95c4-18c96d75d2d5.png)

As you can see the initial entry just looks like a line of JSON and everything does work, it just doesn't look pretty in stackdriver.

What my colleague @malcolmstill is suggesting, is that if instead of using the `log` key, you set the `message` key, then what happens is the same thing. Except that initial entry is actually parsed from the `jsonPayload.message` field and printed just like a normal non json log. Picture shows this better:
![Screenshot 2019-11-27 at 16 10 38](https://user-images.githubusercontent.com/11051419/69741406-e8344c80-1132-11ea-99d0-f87ec91c5f9e.png)

We've had a play around and this seems consistent from running apps in GKE.
```
Client Version: v1.14.7
Server Version: v1.14.7-gke.23
```

Here's a minimal reproduction case using gcloud cli for ease (apologies for my horrendous typos):

```shell
gcloud logging write my-test-log '{ "message": "Show me this text", "id": "1234", "log": "This is my log engtry"}' --payload-type=json --severity=DEBUG

gcloud logging write my-test-log '{"id": "1234", "log": "This is my log engtry"}' --payload-type=json --severity=DEBUG
```

![Screenshot 2019-11-27 at 16 19 59](https://user-images.githubusercontent.com/11051419/69741598-3fd2b800-1133-11ea-9a86-5f3190211815.png)

I have tried to read through the documentation on stackdriver as to why this is parsed differently, but still can't understand exactly why. 
But it would be super handy as you get all the benefits of json (and exporting to big query) but also the messages in stackdriver look more familiar and easily parsable as only the `message` field is initially displayed.

I think `message` field has more tie in to stackdriver debugging too as it may help container multiline errors in logs to a single entry rather than multiple lines.

**Comment by AndrewDryga** [comment]
Oh, I got it @hawksight and I agree that if message would be used by Stackdriver by default we should use it instead of `log`. For me it's weird that they are behaving differently :). Please send a PR or I'll do it myself in the next weeks.
